# Abba Baba - AI Human Collaboration Company
title: "Abba Baba"
description: "Pioneering AI-human collaboration through workflow automation, marketing innovation, and Web3 solutions. Get your time back."
baseurl: ""
url: "https://abbababa.com"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# SEO
author: Abba Baba
twitter:
  username: abbababa
  card: summary_large_image

# Enhanced SEO for AI Discovery
tagline: "Pioneering AI-Human Collaboration"
keywords:
  - "AI automation"
  - "workflow automation"
  - "AI-human collaboration"
  - "marketing automation"
  - "Web3 oracle network"
  - "business process automation"
  - "AI integration services"
  - "intelligent automation"
  - "human-centric AI"
  - "AI validation network"

# AI Crawler Optimization
ai_friendly: true
crawl_priority_pages:
  - "/"
  - "/about/"
  - "/services/"
  - "/faq/"
  - "/riddlen/"
  - "/contact/"

# Custom Abba AI Chat Widget - Public Config
# Private API keys are stored in _config.private.yml (gitignored)
ai_provider: "openai"  # Choose: "openai" or "claude"

# Navigation
header_pages:
  - about.md
  - services.md
  - mycelium.md
  - riddlen.md
  - blog.md
  - faq.md
  - contact.md

# Contact
email: baba@abbababa.com
phone: "+1 (570) 212 - 9613"

# Social
github_username: RiddlenBaba/AbbaBaba
linkedin_username: company/abba-baba

# Analytics
google_analytics: # G-Y2BYSM8WBT
google_tag_manager: G-Y2BYSM8WBT

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
future: true

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Abba Baba Team"
  - scope:
      path: ""
      type: "services"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - claude.md
  - scripts/
  - scripts/venv/
  - "*.py"
  - "*.sh"
  - LOCAL_DEVELOPMENT_NOTES.md
  - GITHUB_ACTIONS_SETUP.md