name: Auto-Generate Blog Category Pages

on:
  push:
    branches: [ main ]
    paths:
      - '_posts/**'
      - 'blog/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-categories:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract categories from posts and generate missing pages
      run: |
        # Create the category directory if it doesn't exist
        mkdir -p blog/category

        # Extract all categories from blog posts
        echo "Extracting categories from blog posts..."
        categories=$(grep -r "^categories:" _posts/ | sed 's/.*categories: *\[\(.*\)\].*/\1/' | tr ',' '\n' | sed 's/^ *//;s/ *$//' | sort -u | grep -v '^$')

        echo "Found categories:"
        echo "$categories"

        # Check which category pages are missing and create them
        for category in $categories; do
          category_file="blog/category/${category}.md"

          if [ ! -f "$category_file" ]; then
            echo "Creating missing category page: $category_file"

            # Generate nice title from slug
            title=$(echo "$category" | sed 's/-/ /g' | sed 's/\b\w/\U&/g')

            # Generate category-specific subtitles
            case "$category" in
              "ai-security")
                subtitle="Enterprise AI security challenges, solutions, and best practices"
                ;;
              "enterprise-strategy")
                subtitle="Strategic insights for enterprise AI adoption and business transformation"
                ;;
              "document-processing")
                subtitle="Intelligent document processing, OCR, and automation workflows"
                ;;
              "ai-workflow")
                subtitle="AI-powered workflows, automation, and process optimization"
                ;;
              "open-source")
                subtitle="Open source AI solutions, technologies, and implementation strategies"
                ;;
              "business-strategy")
                subtitle="Strategic insights for business transformation and growth"
                ;;
              "data-integration")
                subtitle="Data integration patterns, solutions, and best practices"
                ;;
              "ai-architecture")
                subtitle="AI system design, architecture patterns, and implementation strategies"
                ;;
              "mycelium")
                subtitle="Living AI networks and distributed intelligence systems"
                ;;
              "innovation")
                subtitle="Innovation in AI, automation, and human-computer collaboration"
                ;;
              *)
                subtitle="Insights and analysis on $(echo "$category" | sed 's/-/ /g')"
                ;;
            esac

            # Create the category page
            cat > "$category_file" << EOF
---
layout: category
title: "$title"
subtitle: "$subtitle"
category: $category
---
EOF

            echo "Created: $category_file"
          else
            echo "Category page already exists: $category_file"
          fi
        done

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git status --short
        else
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi

    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add blog/category/
        git commit -m "🤖 Auto-generate missing blog category pages

        Automatically created category pages for:
        $(git diff --cached --name-only | sed 's|blog/category/||' | sed 's|\.md||' | tr '\n' ' ')

        Generated by GitHub Actions workflow"
        git push